In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM

models = {
    "0.5B": "Qwen/Qwen2.5-0.5B-Instruct",
    "1.5B": "Qwen/Qwen2.5-1.5B-Instruct",
    "3B": "Qwen/Qwen2.5-3B-Instruct",
    "7B": "Qwen/Qwen2.5-7B-Instruct",
    "14B": "Qwen/Qwen2.5-14B-Instruct",
}

def load_model(model_name):
    print(f"Loading: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto"
    )

    parameters = sum(p.numel() for p in model.parameters())

    print(f"Parameters: {parameters:,}")
    print("Loaded successfully!\n")

    return tokenizer, model

In [3]:
tokenizer, model = load_model(models["0.5B"])

Loading: Qwen/Qwen2.5-0.5B-Instruct

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Parameters: 494,032,768
Loaded successfully!

In [4]:
print(model)

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

In [5]:
print(model.config)

Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.16.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

In [6]:
print("Hidden size:", model.config.hidden_size)
print("Layers:", model.config.num_hidden_layers)
print("Attention heads:", model.config.num_attention_heads)
print("Vocabulary size:", model.config.vocab_size)

Hidden size: 896
Layers: 24
Attention heads: 14
Vocabulary size: 151936

In [7]:
prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)

Explain how a CNC machine works. A CNC (Computer Numerical Control) machine is a type of manufacturing equipment that uses computer technology to control the operation of an industrial machine. It can perform a wide range of tasks, from machining metal parts to producing custom machinery and electronics.

The basic components of a CNC machine include:

1. Electrical system: The electrical system provides power to the machine's motors, drives, and sensors. It also controls the movement of the tool or workpiece.

2. Mechanical system: The mechanical system includes the

In [8]:
import time
import torch

prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

start = time.perf_counter()

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

end = time.perf_counter()

elapsed = end - start

generated_tokens = outputs.shape[1] - inputs["input_ids"].shape[1]

tokens_per_second = generated_tokens / elapsed

print(f"Generated tokens: {generated_tokens}")
print(f"Time: {elapsed:.2f} seconds")
print(f"Tokens/sec: {tokens_per_second:.2f}")

Generated tokens: 100
Time: 20.89 seconds
Tokens/sec: 4.79

In [9]:
tokenizer, model = load_model(models["1.5B"])

Loading: Qwen/Qwen2.5-1.5B-Instruct

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Parameters: 1,543,714,304
Loaded successfully!

In [10]:
tokenizer, model = load_model(models["3B"])

Loading: Qwen/Qwen2.5-3B-Instruct

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Parameters: 3,085,938,688
Loaded successfully!

In [11]:
model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer, model = load_model(model_name)

Loading: Qwen/Qwen2.5-7B-Instruct

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu and disk.

Parameters: 7,615,616,512
Loaded successfully!

In [12]:
from transformers import AutoConfig
import pandas as pd

def inspect_model(size, model_name):
    config = AutoConfig.from_pretrained(model_name)

    width = config.hidden_size
    layers = config.num_hidden_layers
    heads = config.num_attention_heads
    kv_heads = config.num_key_value_heads
    mlp_width = config.intermediate_size
    vocabulary = config.vocab_size
    head_dimension = width // heads

    # Rough transformer scaling measurement
    complexity = layers * width**2

    return {
        "Model": size,
        "Layers": layers,
        "Hidden width": width,
        "Attention heads": heads,
        "KV heads": kv_heads,
        "Head dimension": head_dimension,
        "MLP width": mlp_width,
        "Vocabulary": vocabulary,
        "L × D²": complexity,
    }


results = [
    inspect_model(size, model_name)
    for size, model_name in models.items()
]

comparison = pd.DataFrame(results)
comparison

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

,Model,Layers,Hidden width,Attention heads,KV heads,Head dimension,MLP width,Vocabulary,L × D²
0,0.5B,24,896,14,2,64,4864,151936,19267584
1,1.5B,28,1536,12,2,128,8960,151936,66060288
2,3B,36,2048,16,2,128,11008,151936,150994944
3,7B,28,3584,28,4,128,18944,152064,359661568
4,14B,48,5120,40,8,128,13824,152064,1258291200

In [13]:
baseline = comparison.loc[0, "L × D²"]

comparison["Relative complexity"] = (
    comparison["L × D²"] / baseline
).round(2)

comparison

,Model,Layers,Hidden width,Attention heads,KV heads,Head dimension,MLP width,Vocabulary,L × D²,Relative complexity
0,0.5B,24,896,14,2,64,4864,151936,19267584,1.00
1,1.5B,28,1536,12,2,128,8960,151936,66060288,3.43
2,3B,36,2048,16,2,128,11008,151936,150994944,7.84
3,7B,28,3584,28,4,128,18944,152064,359661568,18.67
4,14B,48,5120,40,8,128,13824,152064,1258291200,65.31

In [18]:
def benchmark_model(
    model_name,
    prompt="Explain how a CNC machine works.",
    max_new_tokens=100,
):
    print(f"Loading {model_name}")

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        dtype="auto",
        device_map="auto",
    )

    model.eval()

    messages = [
        {"role": "user", "content": prompt}
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    input_device = next(model.parameters()).device

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
    ).to(input_device)

    input_tokens = inputs["input_ids"].shape[1]

    # Warm-up
    with torch.inference_mode():
        model.generate(
            **inputs,
            max_new_tokens=5,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()
        torch.cuda.reset_peak_memory_stats()

    start = time.perf_counter()

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start
    generated_tokens = outputs.shape[1] - input_tokens

    result = {
        "Parameters": sum(
            parameter.numel()
            for parameter in model.parameters()
        ),
        "Generated tokens": generated_tokens,
        "Seconds": elapsed,
        "Tokens/sec": generated_tokens / elapsed,
        "Peak GPU memory (GB)": (
            torch.cuda.max_memory_allocated() / 1e9
            if torch.cuda.is_available()
            else 0
        ),
    }

    generated_text = tokenizer.decode(
        outputs[0, input_tokens:],
        skip_special_tokens=True,
    )

    del outputs, inputs, model, tokenizer
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result, generated_text

In [19]:
print(benchmark_model)

<function benchmark_model at 0x77fbcd8aade0>

In [22]:
!pip install -q -U transformers accelerate pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 40.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.

In [23]:
import gc
import time
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM

models_to_test = ["0.5B", "1.5B", "3B"]

benchmark_results = []

for size in models_to_test:
    try:
        result, response = benchmark_model(models[size])

        benchmark_results.append({
            "Model": size,
            **result,
        })

    except torch.cuda.OutOfMemoryError:
        print(f"{size} did not fit in GPU memory.")

        gc.collect()
        torch.cuda.empty_cache()

benchmark_table = pd.DataFrame(benchmark_results)
benchmark_table

Loading Qwen/Qwen2.5-0.5B-Instruct

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Loading Qwen/Qwen2.5-1.5B-Instruct

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Loading Qwen/Qwen2.5-3B-Instruct

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

KeyboardInterrupt:

In [24]:
benchmark_table["FP32 theoretical GB"] = (
    benchmark_table["Parameters"] * 4 / 1e9
)

benchmark_table["FP16 theoretical GB"] = (
    benchmark_table["Parameters"] * 2 / 1e9
)

benchmark_table["Q8 theoretical GB"] = (
    benchmark_table["Parameters"] * 1 / 1e9
)

benchmark_table["Q4 theoretical GB"] = (
    benchmark_table["Parameters"] * 0.5 / 1e9
)

benchmark_table

NameError: name 'benchmark_table' is not defined

In [25]:
import matplotlib.pyplot as plt

plt.plot(
    benchmark_table["Parameters"] / 1e9,
    benchmark_table["Tokens/sec"],
    marker="o",
)

plt.xlabel("Parameters (billions)")
plt.ylabel("Tokens per second")
plt.title("Model Size vs. Generation Speed")
plt.grid(True)
plt.show()

NameError: name 'benchmark_table' is not defined

In [ ]:
def benchmark_model(
    model_name,
    prompt="Explain how a CNC machine works.",
    max_new_tokens=100,
):
    print(f"Loading {model_name}")

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        dtype="auto",
        device_map="auto",
    )

    model.eval()

    messages = [
        {"role": "user", "content": prompt}
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    input_device = next(model.parameters()).device

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
    ).to(input_device)

    input_tokens = inputs["input_ids"].shape[1]

    # Warm-up
    with torch.inference_mode():
        model.generate(
            **inputs,
            max_new_tokens=5,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()
        torch.cuda.reset_peak_memory_stats()

    start = time.perf_counter()

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start
    generated_tokens = outputs.shape[1] - input_tokens

    result = {
        "Parameters": sum(
            parameter.numel()
            for parameter in model.parameters()
        ),
        "Generated tokens": generated_tokens,
        "Seconds": elapsed,
        "Tokens/sec": generated_tokens / elapsed,
        "Peak GPU memory (GB)": (
            torch.cuda.max_memory_allocated() / 1e9
            if torch.cuda.is_available()
            else 0
        ),
    }

    generated_text = tokenizer.decode(
        outputs[0, input_tokens:],
        skip_special_tokens=True,
    )

    del outputs, inputs, model, tokenizer
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result, generated_text

In [ ]:
import gc
import time
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM